### Get list package
GET http://localhost:3000/package

### Get list package
GET http://localhost:3000/package/74c8329e-85e7-11ee-b0fc-089798d3

### Post answer package
POST http://localhost:3000/package/74c8329e-85e7-11ee-b0fc-089798d3
Content-Type: application/json

{
    "most": {
        "1": 11,
        "2": 7,
        "3": 9,
        "4": 6,
        "5": 2
    },
    "least": {
        "1": 1,
        "2": 2,
        "3": 3,
        "4": 3,
        "5": 1
    }
}